### ISSUE TITLE
denied to access property Symbol.toStringTag

### ISSUE THREAD

**Issue by Polyphonus** [akilli/ckeditor5-media#1]
Hi Akilli,

Firstly many thanks for your hard work.

I' m really interested in this plugin but I run into a problem with it and I just begun to work with ckeditor. 

My issue is that when I add a video , once I interact with the video tag (like launching the player). Some error messages starts to appear. (It is working like that with your classic editor demo and the mp4 sample too)

```
Error: Permission denied to access property Symbol.toStringTag 2 ckeditorerror.js:66:2
    o ckeditorerror.js:66
    rethrowUnexpectedError ckeditorerror.js:118
    fire emittermixin.js:244
    n emittermixin.js:235
```

```
Error: Argument 1 of Node.contains does not implement interface Node. ckeditorerror.js:66:2
    o ckeditorerror.js:66
    rethrowUnexpectedError ckeditorerror.js:118
    fire emittermixin.js:244
    change view.js:479
    forceRender view.js:502
    _renderTimeoutId focusobserver.js:40
```

Then when I want to change or retrieve the data :

`Error: cannot-change-view-tree: Attempting to make changes to the view when it is in an incorrect state: rendering or post-fixers are in progress. This may cause some unexpected behavior and inconsistency between the DOM and the view. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-cannot-change-view-tree`

Do you have this issue too?

Can you help me?

I'm not far from my github if you need any additional piece of information.

Have a nice day,

Poly

**Comment by akilli** [comment]
Hi Poly,

thanks for reporting this. Actually, I'm not using the ck5 builds/widgets at the moment, so haven't updated the source code for a while, only the dependencies. So the source code might be outdated. 

I'll have a look.

All the best
Ayhan

**Comment by akilli** [comment]
Could you give me more information/code on what you actually do?

**Comment by Polyphonus** [comment]
I can reproduce in your classic editor demo. 
Steps : 

1. launch classic ediror demo
2. import a video
3. click on the play button in the editor (here come the first error)
4. stop the player (here come the second error)
5. try to import another video or to change the layout insertion mode (here come error number 3)

If the player was not activated , the media can still be deleted. Otherwise not, but no error.

thanks again for your time,

Kef

**Comment by akilli** [comment]
OK, seems only be an issue for videos and only when the video was played. This is no issue for audios as far I see. Correct?

I think, it'd be better to disable the pointer-events for all media elements in editing mode p.e. like in the demo-browser example.This gonna happen anyway as soon I add an additional dialog as in the ck4 version of this widget.

Anyhow, I'll do a quick check what changed in the ck5 api since the source code was updated the last time.

**Comment by akilli** [comment]
Hi Kef,

as a  hotfix I disabled the pointer-events and published new versions of the media widget and the editor builds. Does this fix your problem for the moment?

I'll do the aforementioned check later and release another version if other changes are necessary.

**Comment by Polyphonus** [comment]
Yea that's great. Again thank you for your time.

On more question now that you are there  ^^. I need to limit the number of medias for a given editor.
I already have a way from inside your code but just to be sure ... Is there no "before" and "after" hook (config) for data manipulation .

**Comment by akilli** [comment]
OK. Then I'll close this for now. 

For the other question: I have nothing special in that direction.

**Comment by akilli** [comment]
For the other question again: are you sure that this is not already doable with ckeditor core features?

**Comment by Polyphonus** [comment]
Probably... I keep exploring.
