### ISSUE TITLE
No Media Browser option

### ISSUE THREAD

**Issue by KyooMario** [akilli/ckeditor5-media#3]
Hello Akilli,

I don't want to use a Media Browser just an input box with the appropriate parameters.
Can you advise how to achieve this?

Kind regards,
Mario

**Comment by akilli** [comment]
Hi @KyooMario,

you are actually not limited to a classical _media browser_ implementation. The page you open within the _media browser_ pop-up could also just show a form with a bunch of input elements. The only important thing is the `postMessage()`-call.

Apart from that, you could check out the [media-embed](https://github.com/ckeditor/ckeditor5-media-embed) and [link](https://github.com/ckeditor/ckeditor5-link) plugins? Those are good starting points.

Once I got time again to continue work on this plugin, I will add more functionality. Such an input option is already on my list.
