### ISSUE TITLE
Not compatible with the lastest CKEditor 5 releases

### ISSUE THREAD

**Issue by maz0717** [akilli/ckeditor5-media#4]
The media plugin does not compile with the latest versions of CKEditor 5.  Initial research indicates that there are a number of "BREAKING CHANGES" in various CHANGELOGs.  Some examples:

https://github.com/ckeditor/ckeditor5-engine/blob/master/CHANGELOG.md
States that attachPlaceholder has been renamed to enablePlaceholder and accepts different parameters.
It also seems that the way downcast and upcast converters are handled as been changed.

**Comment by akilli** [comment]
Thanks for reporting. I was already waiting for that release.

**Comment by akilli** [comment]
Please try out v2.0.0
